### ISSUE TITLE
Calculate drawing buffer

### ISSUE THREAD

**Issue by Reon90** [greggman/webgl-memory#10]
https://github.com/greggman/webgl-memory/blob/743348d6f9a893c5da95abb7a4a3c08e8c5259fd/src/utils.js#L113
It's a size of color buffer, it's not a size of canvas.
it means size * depth * depthSize is for 4 times bigger than should be?

**Comment by greggman** [comment]
> It's a size of color buffer, it's not a size of canvas.

Yes, it should have been drawingBufferWidth, drawingBufferHeight instead of canvas.width, canvas.height ([fixed](https://github.com/greggman/webgl-memory/commit/5c861101ab3b5ce291a4e1084fb2ccaa84a7ec30))

> it means size * depth * depthSize is for 4 times bigger than should be?

Right, doh!

[fixed](https://github.com/greggman/webgl-memory/commit/e113f04d78e2857da8fc94ade552edc3a92052f5)
