### ISSUE TITLE
[BUG] when MSAA disable gl.SAMPLES return 1 and gl.SAMPLE_BUFFERS return 0 drawingBuffer should have no resolve texture

### ISSUE THREAD

**Issue by deepkolos** [greggman/webgl-memory#15]
when gl.SAMPLES return 1 && gl.SAMPLE_BUFFERS return 0,  it should have no resolve texture

https://github.com/greggman/webgl-memory/blob/a8ea6ed1909a2b1f914fd408e3293b9048775627/src/utils.js#L122

```js
return size * colorSize + size * (smaples === 1 ? 0 :  smaples) * colorSize + size * depthStencilSize;
```

**Comment by greggman** [comment]
My understanding is that WebGL is always double buffered (having implemented WebGL in Chrome). One texture is given to the compositor. The other is the one you're rendering too. Otherwise, you could end up drawing on the buffer that's being used by the compositor. Since the compositor runs other threads or even another process that's unacceptable.

**Comment by deepkolos** [comment]
@greggman this resolve strategy still works when WebGL runs in mobile device which GPU is tile based rendering? it should be resolve per tile to minimize resolve texture

**Comment by greggman** [comment]
> canvas rendering texture + (resolve texture)? + compositor texture + depth stencil texture

the resolve texture is the compositor texture

There is no guarantee what happens in the browser. It could be quadruple buffereed. It's up to the browser. All we know is that it's supposed to act as though it's double buffered and, if the canvas is multisampled then it may be resolved and that resolve might be directly into the 2nd buffer. 

So, ideally it's one of 2 situations

1. double buffered

   canvas's drawingBuffer is swapped with the compositor's displayBuffer

2. copied

   canvas's drawingBuffer is copied to the compositor's displayBuffer

"resolve" is the same as copy so this is situation 2. resolve the drawingBuffer into the compositor's displayBuffer

Whether the compositor is double or triple buffering its displayBuffer's is unknowable from the webpage. So from the POV of WebGL. There are always 2 textures. One may be multisampled or not. The other is not.

**Comment by deepkolos** [comment]
@greggman it seems `drawing buffer` is not including the `compositor texture` in OpenGL

should `compositor texture` included in WebGL?

and `compositor texture` cannot be seen as `resolve texture` which doesn't exist when no MSAA

![20240905-105729](https://github.com/user-attachments/assets/a5c03a3f-35ab-4d16-981d-8df806a0b2ba)

![20240905-105724](https://github.com/user-attachments/assets/d3bc6f89-4e10-4bf8-a5d5-698c319e1343)

**Comment by greggman** [comment]
I'm not sure what point you're trying to make about no resolve texture. 

OpenGL is not double buffered by default. WebGL is double buffered by default. WebGL is higher level than OpenGL because it includes the canvas. Where as OpenGL doesn't include a drawing buffer at all. It leaves that to EGL.

At a minimum there are 2 textures in WebGL (not OpenGL)

1. The drawing buffer (this may or may not be multi-sampled)
2. The compositor's display buffer (this is not multi-sampled)

The "resolve target" is (2) if (1) is multi-sampled but there are still only 2 textures and there are always at least 2 textures, whether or not a "resolve" happens. "resolve" is just in a sense just fancy word for "copy" (copy with filtering).  We can copy (1) -> (2). We can "resolve" (1) -> (2). We can also swap (1) with (2).

There may be cases were there are 3 or 4 textures but we can't know that. We can only know there are at least 2.

**Comment by deepkolos** [comment]
@greggman thanks for explain
